### ISSUE TITLE
App error: "'state' is not valid. Allowed values are: [pending, in_progress, successful, failed, cancelled, unknown]."

### ISSUE THREAD

**Issue by stunko** [rohit-gohri/jira-ci-cd-integration#73]
When the build failed, the drone sets the status to "failure", which causes an error in the application:  "'state' is not valid. Allowed values are: [pending, in_progress, successful, failed, cancelled, unknown]."

**Build log:**

Connecting to Jira Instance "******"...
1s
2	Connecting via Oauth
1s
3	Environment is "Unknown" (unmapped)...
1s
4	Found cloudId: "xxxxxxxxxxxxxxxx"
1s
5	BranchName: feature/xxxxxxxxxx
1s
6	BranchName: feature/xxxxxxxxxx
1s
7	CommitMessage: xxxxxxxxxx: jira integration: debug failed build
1s
8	IssueKeys: "xxxxxxxxxxx"
1s
9	Sending "build" event
1s
10	Requesting url: https://api.atlassian.com/jira/builds/0.1/cloud/xxxxxxxxxxxxxx/bulk}
2s
11	Build Response:
2s
12	{
2s
13	  "acceptedBuilds": [],
2s
14	  "rejectedBuilds": [
2s
15	    {
2s
16	      "key": {
2s
17	        "pipelineId": "drone-xxxxxxxxxx",
2s
18	        "buildNumber": 23719
2s
19	      },
2s
20	      "errors": [
2s
21	        {
2s
22	          "message": "'state' is not valid. Allowed values are: [pending, in_progress, successful, failed, cancelled, unknown]."
2s
23	        }
2s
24	      ]
2s
25	    }
2s
26	  ]
2s
27	}
2s
28	Error: Invalid build generated:
2s
29	 [
2s
30	  {
2s
31	    "key": {
2s
32	      "pipelineId": "drone-xxxxxxxxxx",
2s
33	      "buildNumber": 23719
2s
34	    },
2s
35	    "errors": [
2s
36	      {
2s
37	        "message": "'state' is not valid. Allowed values are: [pending, in_progress, successful, failed, cancelled, unknown]."
2s
38	      }
2s
39	    ]
2s
40	  }
2s
41	]
2s
42	    at /usr/local/jira-ci-cd-integration/dist/webpack:/jira-ci-cd-integration/src/jira/builds.ts:51:1
2s
43	    at Generator.next (<anonymous>)
2s
44	    at fulfilled (/usr/local/jira-ci-cd-integration/dist/webpack:/jira-ci-cd-integration/node_modules/tslib/tslib.js:114:1)
2s
45	    at processTicksAndRejections (internal/process/task_queues.js:97:5) Failed to send event
2s #

**Comment by rohit-gohri** [comment]
Thanks for reporting the error, will be releasing a new version soon with the fix

**Comment by rohit-gohri** [comment]
Released to docker hub, please retry a failed build. Let me know if you see any other issues
