### ISSUE TITLE
Issue key regex matches invalid Jira keys

### ISSUE THREAD

**Issue by Deadleg** [rohit-gohri/jira-ci-cd-integration#77]
Stumbled upon this when we had a commit message with the date `2022-02`. The issue is with the usage of `\w` which matches letters and numbers.

**Comment by rohit-gohri** [comment]
Good catch

**Comment by sweidmannNF** [comment]
I opened a pull request. Had some problems squashing commits on my fork. Do not be confused by those commits :)

**Comment by rohit-gohri** [comment]
Thanks @sweidmannNF . This is released as 0.5 now
